// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
// This interface is used to define the environment variables for Cloudflare Workers
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env extends Record<string, unknown> {
  // Add environment variables here
}
