// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
// This interface is used to define the environment variables for Cloudflare Workers
interface Env extends {} {
  // Add environment variables here
}
