name: Deploy GenSX Example Workflows

on:
  push:
    branches: [main]
    paths:
      - "examples/client-side-tools/**"
      - "examples/chat-ux/**"
      - "examples/draft-pad/**"
      - "examples/deep-research/**"

jobs:
  deploy-client-side-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Client-Side Tools Workflow
        id: deploy
        uses: ./.github/actions/deploy-gensx
        with:
          org: gensx
          working_directory: examples/client-side-tools
          environment_name: prod
          api_key: ${{ secrets.GENSX_API_KEY }}
          workflow_file: gensx/workflows.ts
          env: |
            GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
            TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}
            MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}

      - name: Deployment summary
        shell: bash
        run: |
          echo "Deployed client-side-tools to: ${{ steps.deploy.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY

  deploy-chat-ux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Chat UX Workflow
        id: deploy
        uses: ./.github/actions/deploy-gensx
        with:
          org: gensx
          working_directory: examples/chat-ux
          environment_name: prod
          api_key: ${{ secrets.GENSX_API_KEY }}
          workflow_file: gensx/workflows.ts
          env: |
            ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
            TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}

      - name: Deployment summary
        shell: bash
        run: |
          echo "Deployed chat-ux to: ${{ steps.deploy.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY
  # TODO: Add secrets for this
  # deploy-draft-pad:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Deploy Draft Pad Workflow
  #       id: deploy
  #       uses: ./.github/actions/deploy-gensx
  #       with:
  #         org: gensx
  #         working_directory: examples/draft-pad
  #         environment_name: prod
  #         api_key: ${{ secrets.GENSX_API_KEY }}
  #         workflow_file: gensx/workflows.ts
  #         env: |
  #           OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
  #           ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
  #           GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
  #           DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
  #           XAI_API_KEY=${{ secrets.XAI_API_KEY }}
  #           MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
  #           COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}
  #           GOOGLE_GENERATIVE_AI_API_KEY=${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
  #           AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
  #           AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #           AWS_REGION=${{ secrets.AWS_REGION }}
  #           AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}
  #           AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}
  #           AZURE_OPENAI_API_VERSION=${{ secrets.AZURE_OPENAI_API_VERSION }}

  #     - name: Deployment summary
  #       shell: bash
  #       run: |
  #         echo "Deployed draft-pad to: ${{ steps.deploy.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY

  deploy-deep-research:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Deep Research Workflow
        id: deploy
        uses: ./.github/actions/deploy-gensx
        with:
          org: gensx
          working_directory: examples/deep-research
          environment_name: prod
          api_key: ${{ secrets.GENSX_API_KEY }}
          workflow_file: gensx/workflows.ts
          env: |
            ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}

      - name: Deployment summary
        shell: bash
        run: |
          echo "Deployed deep-research to: ${{ steps.deploy.outputs.deployment_url }}" >> $GITHUB_STEP_SUMMARY
